name: Application Deployment Workflow
on: 
  push:
  pull_request:
    
jobs:
  test:
    name: Application Testing

    runs-on: ubuntu-latest

    steps:
    - name: Set up GitHub actions
      uses: actions/checkout@v3

    - name: Install NPM
      run: sudo apt install npm

    - name: Run Tests
      run: |
        cd hello-world
        npm test

  build:
    needs: [test]
    name: Application Build
    
    runs-on: ubuntu-latest

    steps:
    - name: Install NPM
      run: sudo apt install npm
      
    - name: Run Build
      run: |
        cd hello-world
        npm start
