name: Application Deployment Workflow
on: 
  push:
  pull_request:
    
jobs:
  test:
    name: Application Testing

    runs-on: ubuntu-latest

    steps:
    - name: Set up GitHub actions
      uses: actions/checkout@v3

    - name: Install Node
      run: sudo apt install nodejs
      
    - name: Run NPM install
      run: |
        cd hello-world/target
        npm install

    - name: Run Tests
      run: |
        cd hello-world/target
        npm test

  build:
    needs: [test]
    name: Container Build
    
    runs-on: ubuntu-latest

    steps:
    - name: Set up GitHub actions
      # We need to set the GitHub actions version to be able to move in the directories of our repository
      uses: actions/checkout@v3
      
    - name: Build Docker Container
      run: |
        cd hello-world/target
        docker build -t infinitycandy/capstoneproject .
